// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Api.Database;

#nullable disable

namespace Service.Api.Database.System
{
    [DbContext(typeof(ServiceDatabaseContext))]
    [Migration("20250910000915_NovoLocationsPadrao")]
    partial class NovoLocationsPadrao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AppService")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocationRisk", b =>
                {
                    b.Property<Guid>("LocationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RiskLimitsId")
                        .HasColumnType("uuid");

                    b.HasKey("LocationsId", "RiskLimitsId");

                    b.HasIndex("RiskLimitsId");

                    b.ToTable("LocationRisk", "AppService");
                });

            modelBuilder.Entity("Service.Api.Service.Authentication.Models.UserCompany", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("UserCompanies", "AppService");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies", "AppService");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Locations", "AppService");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EspId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Modules", "AppService");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.ModuleAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId")
                        .IsUnique();

                    b.ToTable("ModuleAccessTokens", "AppService");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.RiskLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("RiskId");

                    b.ToTable("RiskLimit", "AppService");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Risks.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Risks", "AppService");

                    b.HasDiscriminator<string>("RiskType").HasValue("Risk");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DarkBulbTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("DryBulbTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("SensorDatas", "AppService");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Risks.TermoRisk", b =>
                {
                    b.HasBaseType("Service.Api.Service.SystemManager.Models.Risks.Risk");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MetabolicRate")
                        .HasColumnType("integer");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("TermoRisk");
                });

            modelBuilder.Entity("LocationRisk", b =>
                {
                    b.HasOne("Service.Api.Service.SystemManager.Models.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Api.Service.SystemManager.Models.Risks.Risk", null)
                        .WithMany()
                        .HasForeignKey("RiskLimitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Service.Api.Service.Authentication.Models.UserCompany", b =>
                {
                    b.HasOne("Service.Api.Service.SystemManager.Models.Company", "Company")
                        .WithMany("UserCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Location", b =>
                {
                    b.HasOne("Service.Api.Service.SystemManager.Models.Module", "Module")
                        .WithMany("Locations")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Module", b =>
                {
                    b.HasOne("Service.Api.Service.SystemManager.Models.Company", "Company")
                        .WithMany("Modules")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.ModuleAccessToken", b =>
                {
                    b.HasOne("Service.Api.Service.SystemManager.Models.Module", null)
                        .WithOne("AccessToken")
                        .HasForeignKey("Service.Api.Service.SystemManager.Models.ModuleAccessToken", "ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.RiskLimit", b =>
                {
                    b.HasOne("Service.Api.Service.SystemManager.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Service.Api.Service.SystemManager.Models.Risks.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.SensorData", b =>
                {
                    b.HasOne("Service.Api.Service.SystemManager.Models.Location", "Location")
                        .WithMany("SensorDatas")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Company", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("UserCompanies");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Location", b =>
                {
                    b.Navigation("SensorDatas");
                });

            modelBuilder.Entity("Service.Api.Service.SystemManager.Models.Module", b =>
                {
                    b.Navigation("AccessToken")
                        .IsRequired();

                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
